name: CI/CD Frontend

on:
  push:
    branches: [main, najwa]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build & Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Build Next.js
        run: pnpm run build
        env:
          NEXT_PUBLIC_API_URL: /api
          BACKEND_INTERNAL_URL: http://localhost:8089

      - name: Build Docker image
        run: docker build -t invoice-frontend:${{ github.sha }} .

      - name: Verify image
        run: docker images invoice-frontend
